### ISSUE TITLE
Error on HA start up

### ISSUE THREAD

**Issue by zbeez** [amaximus/water_quality_fvm#7]
Hi amaximus,
this is the error I was presented after HA start-up on the water_quality_fvm sensor:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:682
integration: Sensor (documentation, issues)
First occurred: 21:46:26 (1 occurrences)
Last logged: 21:46:26

water_quality_fvm: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1173, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 884, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 899, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 682, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/config/custom_components/water_quality_fvm/sensor.py", line 125, in async_update
    wqdata = await async_get_wqdata(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/water_quality_fvm/sensor.py", line 50, in async_get_wqdata
    async with self._session.get(url) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.vizmuvek.hu:443 ssl:default [Try again]

**Comment by zbeez** [comment]
Another entry in log just fyi

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:682
integration: Sensor (documentation, issues)
First occurred: March 26, 2024 at 22:18:10 (1 occurrences)
Last logged: March 26, 2024 at 22:18:10

water_quality_fvm: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/water_quality_fvm/sensor.py", line 61, in async_get_wqdata
    async with _session.get(url, timeout=HTTP_TIMEOUT) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 682, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/config/custom_components/water_quality_fvm/sensor.py", line 144, in async_update
    wqdata = await async_get_wqdata(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/water_quality_fvm/sensor.py", line 70, in async_get_wqdata
    await hass.async_add_executor_job(_sleep, 10)
          ^^^^
NameError: name 'hass' is not defined. Did you mean: 'self.hass'?

**Comment by amaximus** [comment]
Fixed it added more debugging info to the latest release. Hopefully that will reveal what connection issue you have.

**Comment by zbeez** [comment]
Thank you for your effort! I restarted Home Assistant after updating to newest version and got 2 error logs

This error originated from a custom integration.

Logger: custom_components.water_quality_fvm.sensor
Source: custom_components/water_quality_fvm/sensor.py:72
integration: water_quality_fvm (documentation, issues)
First occurred: 14:00:27 (1 occurrences)
Last logged: 14:00:27

...and...

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:682
integration: Sensor (documentation, issues)
First occurred: 14:00:28 (1 occurrences)
Last logged: 14:00:28

water_quality_fvm: Error on device update!
Traceback (most recent call last):
  File "/config/custom_components/water_quality_fvm/sensor.py", line 61, in async_get_wqdata
    async with _session.get(url, timeout=HTTP_TIMEOUT) as response:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 682, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1262, in async_device_update
    await self.async_update()
  File "/config/custom_components/water_quality_fvm/sensor.py", line 147, in async_update
    wqdata = await async_get_wqdata(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/water_quality_fvm/sensor.py", line 73, in async_get_wqdata
    await self._hass.async_add_executor_job(_sleep, 10)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/water_quality_fvm/sensor.py", line 47, in _sleep
    time.sleep(secs)
    ^^^^
NameError: name 'time' is not defined. Did you forget to import 'time'


I checked if I can find something to the state of the sensor but the sensor is missing as an entity.

**Comment by amaximus** [comment]
Added a release to fix thie missing module and making the connection issue debugging more generic.

**Comment by zbeez** [comment]
Sensor present again after update and works great. 
The only entry I see now in the log is this rather cryptic one:

This error originated from a custom integration.

Logger: custom_components.water_quality_fvm.sensor
Source: custom_components/water_quality_fvm/sensor.py:73
integration: water_quality_fvm (documentation, issues)
First occurred: 16:04:53 (1 occurrences)
Last logged: 16:04:53

error: {err} of type: {type(err)}

UPDATE: 2.nd restart of Home Assistant does not show any other error logs. 
Thank you for solving this!

**Comment by amaximus** [comment]
Just pushed a release for fixing connection error handling.

**Comment by zbeez** [comment]
The sensor works flawlessly...but there are still 2 log entries worth noticing. Don't know if anybody else has the same issues.

This error originated from a custom integration.

Logger: custom_components.water_quality_fvm.sensor
Source: custom_components/water_quality_fvm/sensor.py:71
integration: water_quality_fvm (documentation, issues)
First occurred: March 29, 2024 at 20:56:35 (5 occurrences)
Last logged: 14:56:35

error: Cannot connect to host www.vizmuvek.hu:443 ssl:default [Try again] of type: <class 'aiohttp.client_exceptions.ClientConnectorError'>

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1232
First occurred: March 29, 2024 at 17:06:32 (303 occurrences)
Last logged: 14:56:40

Update of sensor.bkksensor1 is taking over 10 seconds
Update of sensor.bkksensor2  is taking over 10 seconds
Update of sensor.bkksensor3 is taking over 10 seconds
Update of sensor.water_quality_fvm is taking over 10 seconds

**Comment by amaximus** [comment]
Latest release increases the connection timeout to 1 minute.

**Comment by zbeez** [comment]
It works flawlessly, thank you for all the effort.
